version: '3.1'

services:
  nextjs:
    build: ./frontend
    container_name: nextjs
    ports:
      - 3000:3000
    volumes:
      - ./frontend:/grt
      - /grt/node_modules
    networks:
      - web
    restart: always
networks:
  web:
    name: web
    driver: bridge